### ISSUE TITLE
NFZ.age.plots

### ISSUE THREAD

**Issue by KyleShertzer-NOAA** [mtvincen/FishGraph#21]
Nice to have:
Add the argument last.drop to remove years at the end of the time series. In particular, I'm thinking of the single projection year that BAM sometimes includes (i.e., estimates at the start of the year immediately after the terminal year). In those cases, we probably shouldn't show that year in the plots. It's led to some confusion in the past, requiring extra explanation about why it's different from the assessment years. It can be an unnecessary distraction, so the option to remove it would be nice to have. 

The function already has the argument "first.drop" which was implemented for cases where someone would want to drop the initialization years from the plots. Implementation of last.drop would be analogous to first.drop.

**Comment by mtvincen** [comment]
Would this be for all of the plots (F, Z, and N) or just the abundance?

**Comment by KyleShertzer-NOAA** [comment]
I think any plots that show the projection year. F and Z obviously don't, but N and B might. SSB might as well if it's computed at the start of the year. The plots that caused the most confusion were the stacked bar plots of N at age and B at age, but the argument last.drop could probably just be applied to all N and B plots.

**Comment by mtvincen** [comment]
Added functionality for drop.last.NB as a boolean to NFZ with default option FALSE (Just fixed incorrect documentation).
I also added in plots to create SSB.age if anyone decides to add this to BAM.

**Comment by KyleShertzer-NOAA** [comment]
Nice additions. Thanks, Matt!
