### ISSUE TITLE
StockRec.plots error message

### ISSUE THREAD

**Issue by KyleShertzer-NOAA** [mtvincen/FishGraph#22]
On line 262 of the StockRec.plots function, the error message condition isn't quite right.
It flags when there is a negative log value, which isn't necessarily a problem (logged values can be negative, e.g., log(0.5)).
Change that line to this:
if (any(is.na(logRS)))

**Comment by KyleShertzer-NOAA** [comment]
My reason for suggesting the change to the error message is less about the error message itself. When the error message incorrectly flags, StockRec.plots stops running and fails to make all the plots.

**Comment by mtvincen** [comment]
I noticed this as well a while ago and had updated the code. I just forgot to push it to the main repo. I have done so now
